spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/magnolia
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful
  error:
    include-message: always
    include-stacktrace: never

security:
  jwt:
    header: Authorization
    prefix: "Bearer "
    expiration: 900
    refreshTokenExpiration: 1209600

kakao:
  restApiKey: c338003d85e598b4a1d995e8deb3875a
  localApi:
    url: https://dapi.kakao.com/v2/local/search/keyword.json

naver:
  clientId: kx0ofawL9pR02afxlegj
  clientSecret: DmWmsRITJq
  localApi:
    url: https://openapi.naver.com/v1/search/local.json

--- #dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: securePassword12!@
    url: jdbc:mysql://127.0.0.1:3306/dev-database
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev

--- #prod
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: securePassword12!@
    url: jdbc:mysql://127.0.0.1:3306/prod-database
  jpa:
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: prod