spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/./data/magnolia
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful
  error:
    include-message: always
    include-stacktrace: never

security:
  jwt:
    header: Authorization
    prefix: "Bearer "
    expiration: 900
    refreshTokenExpiration: 1209600

kakao:
  restApiKey: c338003d85e598b4a1d995e8deb3875a
  localApi:
    url: https://dapi.kakao.com/v2/local/search/keyword.json

naver:
  clientId: kx0ofawL9pR02afxlegj
  clientSecret: DmWmsRITJq
  localApi:
    url: https://openapi.naver.com/v1/search/local.json