spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful
  error:
    include-message: always
    include-stacktrace: never

security:
  jwt:
    header: Authorization
    prefix: "Bearer "
    expiration: 900
    refreshTokenExpiration: 1209600