### 서버 상태 체크 API
GET http://localhost:8080/api/v1/health/ping
Accept: application/json


### 아이디 중복 확인 API
GET http://localhost:8080/api/v1/account/isAccountIdExist?accountId=googit
Accept: application/json

### 회원가입 API (취약한 패스워드 -> HTTP 400 에러)
POST http://localhost:8080/api/v1/account/signUp
Content-Type: application/json

{
  "accountId": "googit7",
  "password": "weakpassword"
}

### 회원가입 API (HTTP 200)
POST http://localhost:8080/api/v1/account/signUp
Content-Type: application/json

{
  "accountId": "googit6",
  "password": "strongPassword12!@"
}

> {% client.global.set("accessToken", response.body.accessToken);
client.global.set("refreshToken", response.body.refreshToken);
%}


### 로그인 API
POST http://localhost:8080/api/v1/account/login
Content-Type: application/json

{
  "accountId": "googit6",
  "password": "strongPassword12!@"
}

> {% client.global.set("accessToken", response.body.accessToken);
client.global.set("refreshToken", response.body.refreshToken);
%}


### 리프레쉬 토큰으로 토큰 갱신 API
POST http://localhost:8080/api/v1/auth/refreshToken
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {% client.global.set("accessToken", response.body.accessToken);
if (response.body.refreshToken != null) {
  client.global.set("refreshToken", response.body.refreshToken);
}
%}


### 장소 검색 API
GET http://localhost:8080/api/v1/search/place?keyword=은행
Authorization: Bearer {{accessToken}}


### 장소 검색 API with forceRefresh parameter
GET http://localhost:8080/api/v1/search/place?keyword=은행&forceRefresh=true
Authorization: Bearer {{accessToken}}


### 내 검색 히스토리 API
GET http://localhost:8080/api/v1/histories/me/placeSearch
Authorization: Bearer {{accessToken}}


### 인기 키워드 목록 API
GET http://localhost:8080/api/v1/histories/placeSearch/top10
Authorization: Bearer {{accessToken}}